sudo: required
services:
  - docker
before_install:
  - docker build -t twokdavey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true twokdavey/react-test npm test

after_success:
  - docker build -t twokdavey/multi-client ./client
  - docker build -t twokdavey/multi-nginx ./nginx
  - docker build -t twokdavey/multi-server ./server
  - docker build -t twokdavey/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push twokdavey/multi-client
  - docker push twokdavey/multi-nginx
  - docker push twokdavey/multi-server
  - docker push twokdavey/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-795424185016
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY